# coding=utf-8
__author__ = 'ali'


# noinspection PyClassHasNoInit
class Constants:
    SLEEP_TIME_BEFORE_NEXT_MEASUREMENT_AFTER_BROADCAST = 0.2
    SLEEP_TIME_BEFORE_NEXT_MEASUREMENT_NO_BROADCAST = 0.75

    HEARTBEAT_STARTING = "STARTING"
    HEARTBEAT_GPIO_INITIALIZED = "GPIO_INITIALIZED"
    HEARTBEAT_OPERATIONAL = "HEARTBEAT_OPERATIONAL"
    HEARTBEAT_DIE = "DIE"

    TOO_CLOSE_DISTANCE_THRESHOLD = 30  # TODO: do experiments for this

    EVENT_TYPE_OBJECT_WITHIN_THRESHOLD1 = "OBJECT_WITHIN_THRESHOLD1"
    EVENT_TYPE_OBJECT_WITHIN_THRESHOLD2 = "OBJECT_WITHIN_THRESHOLD2"