__author__ = 'ali'

class Constants:

    HEARTBEAT_STARTING = "STARTING"
    HEARTBEAT_GPIO_INITIALIZED = "GPIO_INITIALIZED"
    HEARTBEAT_DIE = "DIE"

    TOO_CLOSE_DISTANCE_THRESHOLD = 30       # TODO: do experiments for this
    EVENT_TYPE_OBJECT_WITHIN_THRESHOLD1 = "OBJECT_WITHIN_THRESHOLD1"
    EVENT_TYPE_OBJECT_WITHIN_THRESHOLD2 = "OBJECT_WITHIN_THRESHOLD2"